services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: pet_horizon
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
